### ISSUE TITLE
myI

### ISSUE THREAD

**Issue by BabyJ2385** [coder/packages#17]
9 lines (9 sloc)  287 Bytes
FROM ghcr.io/coder/coder:v0.22.0
ENV PORT=3000
ENV CODER_HTTP_ADDRESS=0.0.0.0:$PORT
ARG RAILWAY_STATIC_URL=
ENV CODER_ACCESS_URL=https://$RAILWAY_STATIC_URL
ARG DATABASE_URL
ENV CODER_PG_CONNECTION_URL=$DATABASE_URL
ENV CODER_EXPERIMENTS=*
ENV CODER_TELEMETRY_INSTALL_SOURCE

**Comment by matifali** [comment]
Would you explain the issue?
